services:
  db:
    platform: linux/arm64/v8
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql

  web:
    platform: linux/arm64/v8
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # pry-rails
    stdin_open: true
    tty: true
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webdriver_chrome
    # RSpec SystemTest
    environment:
      SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub

  # RSpec SystemTest
  webdriver_chrome:
    image: seleniarm/standalone-chromium  # Apple Silicon (ARM64)対応のSeleniumイメージ
